variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy


build:
  stage: build
  image: monachus/hugo
  script:
  - hugo -d public_html
  artifacts:
    paths:
    - public_html
  only:
  - source

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client rsync
  script:
  - eval $(ssh-agent -s)
  - ssh-add < (echo -n "$SSH_PRIVATE_KEY" | base64 --decode)
  - mkdir -p ~/.ssh
  - echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
  - rsync -hrvz --delete --exclude=_ -e 'ssh -p 2016' public_html/ "${SSH_USER_HOST_LOCATION}" 
  only:
  - source
