language: go
language: go

install:
  - go get github.com/gohugoio/hugo

env:
  global:
  - SSH_KEY="id_travis"
  - GIT_NAME="Emilien Mottet"
  - GIT_EMAIL="emilien@emottet.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
before_install:
  - openssl aes-256-cbc -K $encrypted_b7db4ef157c2_key -iv $encrypted_b7db4ef157c2_iv -in $SSH_KEY.enc -out $SSH_KEY -d

script:
  - hugo --theme=hugo-theme-nix

after_success:
  - "./scripts/deploy.sh"
