language: go
go:
  - "1.8"

before_install:
  - openssl aes-256-cbc -K $encrypted_b7db4ef157c2_key -iv $encrypted_b7db4ef157c2_iv
  - in travis_key.enc -out ~\/.ssh/travis_key -d
  - go get -u -v github.com/spf13/hugo

script:
  - hugo --theme=hugo-theme-nix