baseURL = "/"
languageCode = "en-us"
title = "Emilien Mottet"
theme = "hugo-theme-nix"

[params]
  GithubID = "EmilienMottet"
  GitlabId = "EmilienMottet"
  TwitterID = "EmilienMottet"
  LinkedInID = "emilien-mottet-78334611a"
#  GoogleplusID = "your_googleplus"
#  FacebookID = "your_facebook"
  Name = "Emilien Mottet"
  HeaderUsername = "emilien"
  HeaderHostname = "blog"
  Email = "emilien@emottet.com"
  About = "I'm Emilien Mottet, a developer and a student."
  ProfilePicture = "/profile-emilien.jpg"
#  GoogleAnalytics = "your_google_analytics_id"
  PayPalMeID = "EmilienMottet"
  TelegramID = "Bibemi"
  StackOverflowID = "8362635"
  CvURL = "https://gitlab.emottet.com/EmilienMotte/cv/-/jobs/artifacts/master/raw/pdf/material-dark.pdf?job=pdf"
  
#[menu]
#[[menu.header]]
#  name = "posts"
#  weight = 0
#  url = "/posts"

